if(!window.supabase){document.getElementById("loginError").textContent="No se pudo cargar la conexión con Supabase. Recarga la página.";throw new Error("Supabase JS no cargó");}
const cfg=window.AMONTI_CONFIG,db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY),$=id=>document.getElementById(id);let courses=[],galleries=[],reviews=[],home=null,slides=[];
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1800)}function money(n){return new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(Number(n||0))}function showTab(name){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));document.querySelectorAll(".panel-section").forEach(x=>x.classList.remove("active"));$("tab-"+name).classList.add("active")}
async function upload(file,folder){const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const r=await db.storage.from(cfg.BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(r.error)throw r.error;return db.storage.from(cfg.BUCKET).getPublicUrl(path).data.publicUrl}
async function verifyAdmin(){const {data:{session}}=await db.auth.getSession();if(!session)return false;const q=await db.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();return !q.error&&!!q.data}
async function authGate(){if(await verifyAdmin()){$("loginView").classList.add("hidden");$("adminApp").classList.remove("hidden");await loadAll()}else{$("loginView").classList.remove("hidden");$("adminApp").classList.add("hidden")}}
async function login(){const r=await db.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(r.error){$("loginError").textContent="No se pudo iniciar sesión.";return}if(!(await verifyAdmin())){await db.auth.signOut();$("loginError").textContent="Este usuario no tiene permisos de administrador.";return}authGate()}
async function loadAll(){const [c,g,r,h,s]=await Promise.all([db.from("courses").select("*").order("created_at",{ascending:false}),db.from("course_gallery").select("*"),db.from("reviews").select("*").order("created_at",{ascending:false}),db.from("home_settings").select("*").limit(1).maybeSingle(),db.from("home_slides").select("*").order("sort_order")]);const err=[c,g,r,h,s].find(x=>x.error);if(err){toast(err.error.message);return}courses=c.data||[];galleries=g.data||[];reviews=r.data||[];home=h.data;slides=s.data||[];renderAdmin();renderHomeEditor()}
function renderAdmin(){$("adminCourses").innerHTML=courses.length?courses.map(c=>`<div class="admin-row"><div class="thumb" style="background-image:url('${c.main_image||""}')"></div><div class="row-main"><strong>${c.name}</strong><small>${money(c.price)} · ${c.published?"Publicado":"Oculto"}</small></div><div class="row-actions"><button class="btn outline edit-course" data-id="${c.id}">Editar</button><button class="btn danger del-course" data-id="${c.id}">Eliminar</button></div></div>`).join(""):`<p class="note">Todavía no hay cursos.</p>`;document.querySelectorAll(".edit-course").forEach(b=>b.addEventListener("click",()=>editCourse(+b.dataset.id)));document.querySelectorAll(".del-course").forEach(b=>b.addEventListener("click",()=>deleteCourse(+b.dataset.id)));renderPending();renderApproved()}
function clearEditor(){["editId","oldMainImage","courseName","coursePrice","courseTag","courseDesc","courseLearn","courseIncludes"].forEach(id=>$(id).value="");$("courseCat").value="Repostería";$("coursePublished").value="true";$("galleryPreview").innerHTML=""}
function editCourse(id){const c=courses.find(x=>x.id===id);$("editId").value=c.id;$("oldMainImage").value=c.main_image||"";$("courseName").value=c.name;$("coursePrice").value=c.price;$("courseCat").value=c.category||"Repostería";$("courseTag").value=c.tag||"";$("courseDesc").value=c.description||"";$("courseLearn").value=(c.learn||[]).join("\n");$("courseIncludes").value=(c.includes||[]).join("\n");$("coursePublished").value=String(c.published);showTab("editor")}
async function saveCourse(){try{const id=+$("editId").value||null;let main=$("oldMainImage").value||null;if($("mainImage").files[0])main=await upload($("mainImage").files[0],"courses");const data={name:$("courseName").value.trim()||"Curso sin nombre",price:+$("coursePrice").value||0,category:$("courseCat").value,tag:$("courseTag").value.trim()||$("courseCat").value,description:$("courseDesc").value.trim(),learn:$("courseLearn").value.split("\n").map(x=>x.trim()).filter(Boolean),includes:$("courseIncludes").value.split("\n").map(x=>x.trim()).filter(Boolean),main_image:main,published:$("coursePublished").value==="true",updated_at:new Date().toISOString()};let cid=id;if(id){const q=await db.from("courses").update(data).eq("id",id).select("id").single();if(q.error)throw q.error;cid=q.data.id}else{const q=await db.from("courses").insert(data).select("id").single();if(q.error)throw q.error;cid=q.data.id}for(const f of [...$("studentImages").files]){const url=await upload(f,`gallery/${cid}`);const q=await db.from("course_gallery").insert({course_id:cid,image_url:url});if(q.error)throw q.error}toast("Curso guardado");clearEditor();await loadAll();showTab("courses")}catch(e){toast(e.message||"No se pudo guardar")}}
async function deleteCourse(id){if(!confirm("¿Eliminar este curso?"))return;const q=await db.from("courses").delete().eq("id",id);if(q.error)return toast(q.error.message);await loadAll()}
function reviewCard(r,pending){const c=courses.find(x=>x.id===r.course_id);return `<div class="pending-card"><div class="status">${c?.name||"Curso"}</div><div class="stars">${"★".repeat(r.stars)}</div><strong>${r.display_name}</strong><p>“${r.comment}”</p>${r.photo_url?`<div style="height:150px;max-width:260px;border-radius:12px;background:url('${r.photo_url}') center/cover;margin:10px 0"></div>`:""}${pending?`<button class="btn approve-review" data-id="${r.id}">✓ Aprobar</button> <button class="btn danger reject-review" data-id="${r.id}">Rechazar</button>`:`<label class="form-check"><input class="feature-review" data-id="${r.id}" type="checkbox" ${r.featured?"checked":""}><span>⭐ Destacar en página principal</span></label><button class="btn danger delete-review" data-id="${r.id}">Eliminar</button>`}</div>`}
function bindReviews(){document.querySelectorAll(".approve-review").forEach(b=>b.addEventListener("click",()=>setReview(+b.dataset.id,{status:"approved"})));document.querySelectorAll(".reject-review").forEach(b=>b.addEventListener("click",()=>setReview(+b.dataset.id,{status:"rejected"})));document.querySelectorAll(".feature-review").forEach(b=>b.addEventListener("change",()=>setReview(+b.dataset.id,{featured:b.checked})));document.querySelectorAll(".delete-review").forEach(b=>b.addEventListener("click",()=>deleteReview(+b.dataset.id)))}
function renderPending(){const l=reviews.filter(r=>r.status==="pending");$("pendingCount").textContent=`${l.length} pendiente(s)`;$("pendingReviews").innerHTML=l.length?l.map(r=>reviewCard(r,true)).join(""):`<p class="note">No hay opiniones pendientes.</p>`;bindReviews()}
function renderApproved(){const l=reviews.filter(r=>r.status==="approved");$("approvedReviews").innerHTML=l.length?l.map(r=>reviewCard(r,false)).join(""):`<p class="note">No hay opiniones aprobadas.</p>`;bindReviews()}
async function setReview(id,patch){const q=await db.from("reviews").update(patch).eq("id",id);if(q.error)return toast(q.error.message);await loadAll()}async function deleteReview(id){if(!confirm("¿Eliminar esta opinión?"))return;const q=await db.from("reviews").delete().eq("id",id);if(q.error)return toast(q.error.message);await loadAll()}
function renderHomeEditor(){$("homeTitle").value=home?.title||"Aprende. Hornea. Disfruta.";$("homeText").value=home?.welcome_text||"";$("slideSeconds").value=home?.slide_seconds||2;$("nextCourseName").value=home?.next_course_name||"Próximo curso";$("nextCourseSubtitle").value=home?.next_course_subtitle||"Muy pronto";$("nextPreview").innerHTML=slides.map(s=>`<div class="pic" style="background-image:url('${s.image_url}')"></div>`).join("")}
async function saveHome(){try{const data={title:$("homeTitle").value.trim()||"Aprende. Hornea. Disfruta.",welcome_text:$("homeText").value.trim(),slide_seconds:Math.max(2,+$("slideSeconds").value||2),next_course_name:$("nextCourseName").value.trim()||"Próximo curso",next_course_subtitle:$("nextCourseSubtitle").value.trim()||"Muy pronto",updated_at:new Date().toISOString()};if(home?.id){const q=await db.from("home_settings").update(data).eq("id",home.id);if(q.error)throw q.error}else{const q=await db.from("home_settings").insert(data);if(q.error)throw q.error}let order=slides.length;for(const f of [...$("nextCourseImages").files]){const url=await upload(f,"home");const q=await db.from("home_slides").insert({image_url:url,sort_order:order++});if(q.error)throw q.error}toast("Portada guardada");await loadAll()}catch(e){toast(e.message||"No se pudo guardar")}}
$("loginBtn").addEventListener("click",login);$("logoutBtn").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));$("newCourseBtn").addEventListener("click",()=>{clearEditor();showTab("editor")});$("saveCourseBtn").addEventListener("click",saveCourse);$("cancelEditBtn").addEventListener("click",()=>{clearEditor();showTab("courses")});$("saveHomeBtn").addEventListener("click",saveHome);authGate();